services:
  mysql:
    container_name: vacchuncc_mysql_v2_staging
    image: mysql:8.0.36
    env_file:
      - .env.staging
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent || exit 1']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
  phpmyadmin:
    container_name: vacchuncc_pma_v2_staging
    depends_on:
      mysql:
        condition: service_started
    image: phpmyadmin:5.2.3-apache
    ports:
      - "8080:80"
    env_file:
      - .env.staging
    restart: unless-stopped
  backend:
    image: csabi44/vacchuncc_backend:staging
    container_name: vacchuncc_backend_v2_staging
    ports:
      - 4000:4000
    env_file:
      - .env.staging
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:3000"]
      interval: 1m0s
      timeout: 5s
      retries: 3
      start_period: 45s
      start_interval: 5s
  frontend:
    image: csabi44/vacchuncc_frontend:staging
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
volumes:
  mysql_data:
