name: Docker build check

on:
  push:
    branches: [dev, main]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Backend Dockerfile build check
        run: docker build --target=prod --no-cache ./backend

      - name: Frontend Dockerfile build check
        run: docker build --target=prod --no-cache ./frontend
